# Generated by Django 3.1.6 on 2021-02-16 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechdesing_app.sensor')),
            ],
        ),
    ]
